name: OperatorFromPerms
version: 2.0.0
main: com.gordey9992.operatorfromperms.OperatorFromPerms
api-version: 1.21
description: Дает права оператора через разрешение LuckPerms + система авторизации
authors: [gordey25690, DeepSeek]
website: https://github.com/gordey9992/OperatorFromPerms
depend: [LuckPerms]

commands:
  operatorfromperms:
    description: Управление плагином OperatorFromPerms
    aliases: [opf]
    permission: operatorfromperms.admin
    usage: /<command> <reload|check|version>
  register:
    description: Регистрация в системе
    aliases: [reg, регистрация, рег, регистр]
    usage: /<command> <пароль> <подтверждение>
  login:
    description: Вход в систему
    aliases: [log, l, логин, л, auth]
    usage: /<command> <пароль>
  remember:
    description: Запомнить меня на 24 часа
    aliases: [запомнить, rememberme]
    usage: /<command>

permissions:
  operatorfromperms.admin:
    description: Доступ к командам администрирования плагина
    default: op
  operatorfromperms.all:
    description: Дает права оператора через разрешение
    default: false
